# First session

This is the first session of our Python class.


1. Install Anaconda (3.7.x) from [here](https://docs.anaconda.com/anaconda/packages/old-pkg-lists/2021.04/py3.7_win-64/)

2. Install IDE. (PyCharm)

3. Virtual Environment (Conda) 

```
conda create --prefix=D:path/to/your/folder --no-default-packages python=3.6 numpy pandas
```







$\ln{\sqrt{5x^2}}$

## Python Data Types

* list   --> [], list()
* set   --> {}, set()
* dictionary  --> {'Key': Value, ...}, dist()
* tuple  --> (), tuple()
* character / string
* numerical

In [ ]:
counter = 1100
name = 'Ahmad'
var1 = 1.5

print(type(counter))
print(type(name))
print(type(var1))

<class 'int'>
<class 'str'>
<class 'float'>


In [ ]:
LIST = [1, 2, 9, 10, 5, 'ali', 5.68, [1, 8, 9]]
print(LIST)

[1, 2, 9, 10, 5, 'ali', 5.68, [1, 8, 9]]


In [ ]:
A = [1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3]
print(A)

B = {5, 8, 9, 1, 2, 1, 1, 2}
print(B)

C = set(A)
print(C)

[1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3]
{1, 2, 5, 8, 9}
{1, 2, 3, 4, 6, 8, 9}


In [ ]:
d = {'name': ['Ali', 'Hosein', 'Bob'],
     'age': [18, 25, 36]}

print(d)

{'name': ['Ali', 'Hosein', 'Bob'], 'age': [18, 25, 36]}


In [ ]:
t = (5, 8, 9, 1, 2, 2)
print(type(t), t)

<class 'tuple'> (5, 8, 9, 1, 2, 2)


### Indexing


In [ ]:
print(A, A[4])

[1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3] 3


In [ ]:
C[2]

TypeError: ignored

In [ ]:
print(A)
A[6] = 14
print(A)

[1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3]
[1, 8, 9, 6, 3, 4, 14, 2, 2, 2, 3]


In [ ]:
print(t)
print(t[3])

# Tuples are immutable (/mutable).
t[3] = 84
print(t)

(5, 8, 9, 1, 2, 2)
1


TypeError: ignored

In [ ]:
print(d)
d['age'][0]         # multi-indexing

# a(2) --> f(x) = function

D = {'name': ['a', 'b', 'c'],
     'number': [[2, 3], [4, 5], [5, 6]]}
print(D)
print(D['number'][1][0])

{'name': ['Ali', 'Hosein', 'Bob'], 'age': [18, 25, 36]}
{'name': ['a', 'b', 'c'], 'number': [[2, 3], [4, 5], [5, 6]]}
4


## Operators

1. *
2. +
3. /
4. -
5. **
6. @
7. %

In [ ]:
print([1, 2, 3] + [8, 6, 9])

print('Hello World!' * 2)
print('a' * 20)

s = 'Hello World!'
print(s[-6:-1])      # a(end - 1)

# [ 2 , 5 )     --> include , exclude
print(s[-6:])
print(s[:5])

print(s + ' Ali ' + s)

[1, 2, 3, 8, 6, 9]
Hello World!Hello World!
aaaaaaaaaaaaaaaaaaaa
World
World!
Hello
Hello World! Ali Hello World!


In [ ]:
student_number = 98111256
name = 'John Adams'

# John Adams student number is 98111256.

print(name + ' student number is ' + str(student_number) + '.')       # casting
print('{0} student number is {1}.'.format(name, student_number))

John Adams student number is 98111256.
John Adams student number is 98111256.


In [ ]:
# Logical operators
A = [1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3]

print(A)
print([1, 2] in A)

A = A + [[1, 2]]
print([1, 2] in A)

print(type(A) is tuple)

[1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3]
False
True
False


In [ ]:
a = b = c = 5
print(a, b, c)

d, e, f = 8, 9, 10
print(d, e, f)

5 5 5
8 9 10


In [ ]:
print(a)
print(c)

5
5


### if / for / while

In [ ]:
i = 0
if i < 10:
    print(i)
    b = 2
    print(b)

print('Out')

0
2
Out


In [ ]:
A

[1, 8, 9, 6, 3, 4, 4, 2, 2, 2, 3, [1, 2]]

In [ ]:
counter = 1

for i in range(10, 20):         # for i = 1:10
    print(counter)
    counter += i

print('---------------------------')
for j in A:     # enumerate
    print(j * 3)

1
11
22
34
47
61
76
92
109
127
---------------------------
3
24
27
18
9
12
12
6
6
6
9
[1, 2, 1, 2, 1, 2]


# Numpy (numerical python)

In [ ]:
import numpy as np

In [ ]:
Ar = np.array([1, 5, 3, 6, 8])
print(Ar[4])

Br = np.array([7, 8, 9, 3, 5])
print(Ar + Br)

print(Ar * Br)

print(Ar @ Br)
print(sum(Ar * Br))

8
[ 8 13 12  9 13]
[ 7 40 27 18 40]
132
132


In [ ]:
print(Ar.shape)
print(type(Br.shape))
print(Br.shape)

(5,)
<class 'tuple'>
(5,)


In [ ]:
Cr = np.array([[1, 2, 3, 4]])
print(Cr)
print(Cr.shape)
print(np.ndim(Cr))

Dr = np.array([[1, 2, 3], [4, 5, 6]])
print(Dr, Dr.shape)

Er = np.zeros(Dr.shape, dtype=int)
print(Er)
Fr = np.zeros_like(Dr)
print(Fr)

[[1 2 3 4]]
(1, 4)
2
[[1 2 3]
 [4 5 6]] (2, 3)
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
